export const Users = [
  {
    id:1,
    profilePicture: "1.jpg",
    username: "Vasily Petrovich",
  },
  {
    id:2,
    profilePicture: "2.jpg",
    username: "Janett Jackson",
  },
  {
    id:3,
    profilePicture: "3.jpg",
    username: "Roman Smirn",
  },
  {
    id:4,
    profilePicture: "4.jpg",
    username: "Nikita Sergeich",
  },
  {
    id:5,
    profilePicture: "5.jpg",
    username: "Bimbo Bombo",
  },
  {
    id:6,
    profilePicture: "6.jpg",
    username: "Jembo Jambo",
  },
  {
    id:7,
    profilePicture: "7.jpg",
    username: "Mukembe Diaz",
  },
  {
    id:8,
    profilePicture: "8.jpg",
    username: "Sbeben Schlunz",
  },
  {
    id:9,
    profilePicture: "9.jpg",
    username: "Mehmet Ozdoev",
  },
  {
    id:10,
    profilePicture: "10.jpg",
    username: "Sabih V Pite",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Let me speak from my heart in English",
    photo: "11.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "12.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every planet we reach is dead.",
    photo: "13.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "14.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "15.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "16.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "I feel like I need to pay attention to what I say",
    photo: "17.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "18.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "1+1=2!",
    photo: "19.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "12.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];